---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build-8
  commands:
  - docker build -t pdr.nephatrine.net/nephatrine/nginx-php:8 .
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/nginx-php:8
  - docker tag pdr.nephatrine.net/nephatrine/nginx-php:8 nephatrine/nginx-php:8
  - HOME=/mnt/config/home docker push nephatrine/nginx-php:8
  - docker rmi pdr.nephatrine.net/nephatrine/nginx-php:8
- name: build-latest
  commands:
  - docker tag nephatrine/nginx-php:8 pdr.nephatrine.net/nephatrine/nginx-php:latest
  - HOME=/mnt/config/home docker push pdr.nephatrine.net/nephatrine/nginx-php:latest
  - docker tag pdr.nephatrine.net/nephatrine/nginx-php:latest nephatrine/nginx-php:latest
  - HOME=/mnt/config/home docker push nephatrine/nginx-php:latest
  - docker rmi pdr.nephatrine.net/nephatrine/nginx-php:latest
  depends_on:
  - build-8

---
kind: pipeline
name: after

steps:
- name: notify
  image: appleboy/drone-discord
  settings:
    avatar_url: https://nephatrine.net/images/buttons/drone-ci.png
    message: "Automated build of **{{repo.name}}:{{commit.branch}}** has returned [{{build.status}}]({{build.link}})."
    username: DroneCI
    webhook_id:
      from_secret: wh-infra-id
    webhook_token:
      from_secret: wh-infra-tok

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: pipeline
name: propogate

steps:
- name: trigger
  image: plugins/downstream
  settings:
    server: https://ci.nephatrine.net
    token:
      from_secret: drone-auth
    fork: false
    repositories:
      - nephatrine/docker-nginx-h5ai@master

depends_on:
- default

---
kind: signature
hmac: 0a2815f10f47b9f096bd0c4ef9e75b65d3861efeda11d8514b47ba67df71e5e2

...
