#!/usr/bin/with-contenv bash

HOME=/mnt/config/home

if [[ ! -f /mnt/config/etc/php.ini ]]; then
  s6-setuidgid guardian cp /etc/php/php.ini /mnt/config/etc/php.ini
fi

if [[ ! -d /mnt/config/etc/php.d ]]; then
  s6-setuidgid guardian mkdir -p /mnt/config/etc/php.d
  s6-setuidgid guardian cp -n /etc/php/php.d/* /mnt/config/etc/php.d/
fi